version: '3.7'

services:
    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-bot_db}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - ./env/db:/var/lib/mysql
        networks:
            - app-newtwork

    app:
        build: application
        restart: ${DOCKER_RESTART:-no}
        depends_on:
            - db
        links:
            - db:db_mysql
        volumes:
            - ./:/app
        working_dir: /app
        ports:
            - "${BACKEND_HOST_PORT}8000"
        stdin_open: true
        tty: true
        networks:
            - app-newtwork
            - nginx-gateway
        command: ${RUNSERVER:-/bin/bash}
        environment:
            VIRTUAL_HOST: cloudia03.lfvilella.com
            VIRTUAL_HOST_ALIAS: www.cloudia03.lfvilella.com
            LETSENCRYPT_HOST: cloudia03.lfvilella.com,www.cloudia03.lfvilella.com
            LETSENCRYPT_EMAIL: vilella.luisfelipe+cloudia03.lfvilella.com@gmail.com

networks:
    app-newtwork:
    nginx-gateway:
        external:
            name: nginx-gateway
