version: '3.7'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-'db'}
            MYSQL_USER: ${MYSQL_USER:-'user'}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-'password'}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-'password'}
        volumes:
            - ./env/db:/var/lib/mysql/data
        networks:
            - app-newtwork

    app:
        build: application
        restart: ${DOCKER_RESTART:-no}
        depends_on:
            - db
        volumes:
            - ./:/app
        working_dir: /app/application
        ports:
            - "${BACKEND_HOST_PORT}8000"
        stdin_open: true
        tty: true
        networks:
            - app-newtwork
        command: ${RUNSERVER:-/bin/bash}

networks:
    app-newtwork:
